### ISSUE TITLE
YATA -OC Error: [object Object]

### ISSUE THREAD

**Issue by Phil01388** [TotallyNot/yata-oc#2]
I have the abovementioned error
YATA -OC
Error: [object Object]

on my faction page - shown above the OC list. The values for NNB are shown though, it's still a little annoying tbh...

**Comment by TotallyNot** [comment]
Thank you for the report. I can't really say what the underlying error is, but the newest version of the script I just released should have the error display fixed. Could you update it and tell me what it says?

**Comment by Phil01388** [comment]
Hey, thanks a lot! Now it says:

Error: error is not defined (from TornStats)

I have a TornStats account and it works but I can't find any options that
could be connected to this..

Am Mi., 17. Feb. 2021 um 13:40 Uhr schrieb TotallyNot <
notifications@github.com>:

**Comment by TotallyNot** [comment]
My bad, there was another bug in the error handling for torn stats API requests. That should be fixed in the newest version and it should now properly display the reason for the error.

**Comment by TotallyNot** [comment]
I assume that this has to do with faction API access, but the error message should shed some light on that.
